### PR TITLE
Update MapGenerator.java

### PR DESCRIPTION
**Pull request by sbrad044**
Added import statement for items folder

### CODE REVIEW

**Review by 6167656e74323431 — CHANGES_REQUESTED** [review]
Why is this separate from #52 ? Why is this separate from #51 ? IMO it is sufficient to just make these changes as part of #51 and they’ll get integrated when that’s merged (instead of having to merge these changes back int #51)

**Comment by sbrad044** [comment]
> Why is this separate from #52 ? Why is this separate from #51 ? IMO it is sufficient to just make these changes as part of #51 and they’ll get integrated when that’s merged (instead of having to merge these changes back int #51)

that would require #51 to get approved in the next century though lol

**Comment by 6167656e74323431** [comment]
> Also MapGenerator doesn't exist in #51 so there will be no changes to make when #51 is approved

On the contrary, MapGenerator does exist in #51, it was implicitly added when you merged main into your branch in 11b88a4

**Comment by sbrad044** [comment]
> > Also MapGenerator doesn't exist in #51 so there will be no changes to make when #51 is approved
> 
> On the contrary, MapGenerator does exist in #51, it was implicitly added when you merged main into your branch in [11b88a4](https://github.com/CSC207-2022F-UofT/course-project-group-105/commit/11b88a4c6dca04c26e6488e139a1782ee262a34f)

Ok well I dont see it on my computer, and also I can't figure out how to combine the two pull requests, so perhaps we can just approve this one separately

**Pull request closed without merging**
