### PR TITLE
Implement the Doorway and add basic features and behaviors.

### PR DESCRIPTION
**Pull request by hoodiexxx**
This pull request is for my version of Doorway.
it just a rough draft for Doorway, I store the position for room by integer and it has some methods for you to get the private instance attributes. But it doesn't have any collaboration with Room which need to be implemented later.

### CODE REVIEW

**Review by sbrad044 — APPROVED** [review]

**Review by m-grigoriu — DISMISSED** [review]
Not sure how an integer can represent a position on a 2D map. Looks good otherwise.

**Review by zhaoan12 — DISMISSED** [review]
The class is looking well made. One thing you can consider is changing the variable name NextRoomPosition to nextRoomPosition,  since for variables, the Java naming convention is to start with a lowercase letter and then capitalize the first letter of every subsequent word.

**Comment by hoodiexxx** [comment]
> Not sure how an integer can represent a position on a 2D map. Looks good otherwise.

I believe int could be the index for array or key id for hash map, as I am not sure how exactly the map and rooms would be implemented.

**Review by 6167656e74323431 — CHANGES_REQUESTED** [review]

**Review by 6167656e74323431 — APPROVED** [review]
LGTM

**Review by zhaoan12 — APPROVED** [review]

**Comment by 6167656e74323431** [comment]
Merged during weekly meeting.

**Pull request merged**
